options:
  bgp-speakers:
    type: string
    default: ""
    description: |
      YAML defining a list of speaker configurations. Multiple speakers can be defined as separate list entries
      Example:
      - name: my-speaker
        node-selector: juju-application=kubernetes-worker
        neighbor-address: 10.32.32.1
        neighbor-as: 65030
        cluster-as: 65000
        announce-cluster-ip: true
        v: 2
  control-plane-node-label:
    type: string
    default: "juju-application=kubernetes-control-plane"
    description: |
      Node label for selecting nodes to host the Kube-OVN control plane.
  default-cidr:
    type: string
    default: "192.168.0.0/16"
    description: |
      Default pod CIDR
  default-gateway:
    type: string
    default: "192.168.0.1"
    description: |
      Default gateway for the pod network
  default-grafana-namespace:
    type: string
    default: "kube-ovn-grafana-agent"
    description: |
      Default namespace for the grafana agent deployment (This value cannot be changed after deployment).
  image-registry:
    type: string
    default: ""
    description: |
      Image registry for the kube-ovn image.
  node-switch-cidr:
    type: string
    default: "100.64.0.0/16"
    description: |
      CIDR for node switch (This value requires additional steps/procedures to be changed. Refer to 
      the charm docs for more information).
  node-switch-gateway:
    type: string
    default: "100.64.0.1"
    description: |
      Gateway for node switch (This value requires additional steps/procedures to be changed. Refer to 
      the charm docs for more information).
  pinger-external-address:
    type: string
    default: "8.8.8.8"
    description: |
      External IP address used by kube-ovn-pinger for connectivity testing.
  pinger-external-dns:
    type: string
    default: "google.com"
    description: |
      External DNS hostname used by kube-ovn-pinger for connectivity testing.
