options:
  control-plane-node-label:
    type: string
    default: "juju-application=kubernetes-control-plane"
    description: |
      Node label for selecting nodes to host the Kube-OVN control plane.
  default-cidr:
    type: string
    default: "192.168.0.0/16"
    description: |
      Default pod CIDR
  default-gateway:
    type: string
    default: "192.168.0.1"
    description: |
      Default gateway for the pod network
  node-switch-cidr:
    type: string
    default: "100.64.0.0/16"
    description: |
      CIDR for node switch (This value cannot be changed after deployment).
  node-switch-gateway:
    type: string
    default: "100.64.0.1"
    description: |
      Gateway for node switch (This value cannot be changed after deployment).
  pinger-external-address:
    type: string
    default: "8.8.8.8"
    description: |
      External IP address used by kube-ovn-pinger for connectivity testing.
  pinger-external-dns:
    type: string
    default: "google.com"
    description: |
      External DNS hostname used by kube-ovn-pinger for connectivity testing.
  registry:
    type: string
    default: "rocks.canonical.com"
    description: |
      Image registry for the kube-ovn image.