{
 "title": "Kube-OVN / Kube-OVN-CNI",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "instance",
    "query": "label_values(process_cpu_seconds_total{job=\"kube-ovn-cni\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Up",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(up{job=\"kube-ovn-cni\"})"
    }
   ]
  },
  {
   "title": "CNI Operations Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 3, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(cni_op_latency_seconds_count{job=\"kube-ovn-cni\", instance=~\"$instance\"}[5m])) by (instance, method, status_code)",
     "legendFormat": "{{instance}} {{method}} {{status_code}}"
    }
   ]
  },
  {
   "title": "CNI Operation Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "delta(cni_op_latency_seconds_sum{instance=~\"$instance\"}[5m])/delta(cni_op_latency_seconds_count{instance=~\"$instance\"}[5m])",
     "legendFormat": "{{instance}} {{method}} {{status_code}}"
    }
   ]
  },
  {
   "title": "Error Log in 10 Minutes",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(klog_lines_total{level=\"ERROR\", instance=~\"$instance\", job=\"kube-ovn-cni\"}[10m]))"
    }
   ]
  },
  {
   "title": "OVS Client Request Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 3, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(delta(ovs_client_request_latency_milliseconds_count{job=\"kube-ovn-cni\", instance=~\"$instance\"}[1m])) by (instance, code)",
     "legendFormat": "{{instance}} {{code}}"
    }
   ]
  },
  {
   "title": "OVS Client Request Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "(sum(delta(ovs_client_request_latency_milliseconds_sum{job=\"kube-ovn-cni\", instance=~\"$instance\"}[1m])) by (instance, code))/(sum(delta(ovs_client_request_latency_milliseconds_count{job=\"kube-ovn-cni\", instance=~\"$instance\"}[1m])) by (instance, code))",
     "legendFormat": "{{instance}} {{code}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"kube-ovn-cni\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Goroutine",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{job=\"kube-ovn-cni\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"kube-ovn-cni\", instance=~\"$instance\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Client-Go Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(rest_client_request_latency_seconds_sum{job=\"kube-ovn-cni\", instance=~\"$instance\"}[5m])/rate(rest_client_request_latency_seconds_count{job=\"kube-ovn-cni\", instance=~\"$instance\"}[5m])",
     "legendFormat": "{{instance}} {{verb}}"
    }
   ]
  }
 ]
}