{
 "title": "Kube-OVN / Controller",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "instance",
    "query": "label_values(process_cpu_seconds_total{job=\"kube-ovn-controller\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Up",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "min",
   "targets": [
    {
     "expr": "sum(up{job=\"kube-ovn-controller\"})"
    }
   ]
  },
  {
   "title": "Error Log in 10 Minutes",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "min",
   "targets": [
    {
     "expr": "sum(increase(klog_lines_total{level=\"ERROR\", job=\"kube-ovn-controller\", instance=~\"$instance\"}[10m]))"
    }
   ]
  },
  {
   "title": "Work Queue Add Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(workqueue_adds_total{job=\"kube-ovn-controller\", instance=~\"$instance\"}[5m])) by (instance, name)",
     "legendFormat": "{{instance}} {{name}}"
    }
   ]
  },
  {
   "title": "Work Queue Retry Count ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(delta(workqueue_retries_total{job=\"kube-ovn-controller\", instance=~\"$instance\"}[5m])) by (instance, name)",
     "legendFormat": "{{instance}} {{name}}"
    }
   ]
  },
  {
   "title": "Work Queue Depth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "workqueue_depth{job=\"kube-ovn-controller\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}} {{name}}"
    }
   ]
  },
  {
   "title": "Work Queue Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "(sum(delta(workqueue_queue_duration_seconds_sum{instance=~\"$instance\"}[5m])) by (instance))/(sum(delta(workqueue_queue_duration_seconds_count{instance=~\"$instance\"}[5m])) by (instance))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "OVS Client Request Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(delta(ovs_client_request_latency_milliseconds_count{job=\"kube-ovn-controller\", instance=~\"$instance\"}[1m])) by (instance, db, code )",
     "legendFormat": "{{instance}} {{db}} {{code}}"
    }
   ]
  },
  {
   "title": "OVS Client Request Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "(sum(delta(ovs_client_request_latency_milliseconds_sum{job=\"kube-ovn-controller\", instance=~\"$instance\"}[1m])) by (instance, db, code))/(sum(delta(ovs_client_request_latency_milliseconds_count{job=\"kube-ovn-controller\", instance=~\"$instance\"}[1m])) by (instance, db, code))",
     "legendFormat": "{{instance}} {{db}} {{code}}"
    }
   ]
  },
  {
   "title": "Kube API Request Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(rest_client_requests_total{job=\"kube-ovn-controller\", instance=~\"$instance\",code=~\"2..\"}[5m]))",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(rate(rest_client_requests_total{job=\"kube-ovn-controller\", instance=~\"$instance\",code=~\"3..\"}[5m]))",
     "legendFormat": "3xx"
    },
    {
     "expr": "sum(rate(rest_client_requests_total{job=\"kube-ovn-controller\", instance=~\"$instance\",code=~\"4..\"}[5m]))",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(rate(rest_client_requests_total{job=\"kube-ovn-controller\", instance=~\"$instance\",code=~\"5..\"}[5m]))",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Request Latency 99th Quantile",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 37 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(rest_client_request_latency_seconds_bucket{job=\"kube-ovn-controller\", instance=~\"$instance\"}[5m])) by (verb, url, le))",
     "legendFormat": "{{verb}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"kube-ovn-controller\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 44 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"kube-ovn-controller\",instance=~\"$instance\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{job=\"kube-ovn-controller\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}