{
 "title": "Kube-OVN / OVN",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "instance",
    "query": "label_values(process_cpu_seconds_total{job=\"kube-ovn-monitor\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "OVN DB Up",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(up{job=\"kube-ovn-monitor\"})"
    }
   ]
  },
  {
   "title": "Chassis Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(kube_ovn_chassis_info{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "OVN NB Role",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_ovn_cluster_role{instance=~\"$instance\", db_name=\"OVN_Northbound\"}) by (server_role)",
     "legendFormat": "{{server_role}}"
    }
   ]
  },
  {
   "title": "OVN SB Role",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_ovn_cluster_role{instance=~\"$instance\", db_name=\"OVN_Southbound\"}) by (server_role)",
     "legendFormat": "{{server_role}}"
    }
   ]
  },
  {
   "title": "Logical Switch Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_ovn_logical_switch_info{instance=~\"$instance\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Logical Switch Port Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_ovn_logical_switch_ports_num{instance=~\"$instance\"}",
     "legendFormat": "{{instance}} {{logical_switch_name}}"
    }
   ]
  },
  {
   "title": "DB File Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_ovn_db_file_size_bytes{instance=~\"$instance\", hostname!=\"localhost\"}",
     "legendFormat": "{{instance}} {{db_name}}"
    }
   ]
  },
  {
   "title": "OVN Log File Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_ovn_log_file_size_bytes{instance=~\"$instance\", hostname!=\"localhost\"}",
     "legendFormat": "{{instance}} {{component}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{pod=~\"ovn-central.*\", container!=\"POD\"}) by (pod, node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_memory_working_set_bytes{pod=~\"ovn-central.*\", container!=\"POD\"}) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  }
 ]
}