{
 "title": "Kube-OVN / Pinger",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "instance",
    "query": "label_values(process_cpu_seconds_total{job=\"kube-ovn-pinger\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "OVS Up",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    { "expr": "sum(pinger_ovs_up)" }
   ]
  },
  {
   "title": "OVS Up",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    { "expr": "sum(pinger_ovs_up)" }
   ]
  },
  {
   "title": "OVN-Controller Up",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sum(pinger_ovn_controller_up)" }
   ]
  },
  {
   "title": "OVN-Controller Down",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(pinger_ovn_controller_down)"
    }
   ]
  },
  {
   "title": "DNS Accessible",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(pinger_internal_dns_healthy)"
    }
   ]
  },
  {
   "title": "DNS Unaccessible",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(pinger_internal_dns_unhealthy)"
    }
   ]
  },
  {
   "title": "APIServer Accessible",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sum(pinger_apiserver_healthy)" }
   ]
  },
  {
   "title": "APIServer Unaccessible",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(pinger_apiserver_unhealthy)"
    }
   ]
  },
  {
   "title": "Error Log in 10 Minutues",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(increase(klog_lines_total{level=\"ERROR\", instance=~\"$instance\", job=\"kube-ovn-pinger\"}[10m]))"
    }
   ]
  },
  {
   "title": "ApiServer Latency Avg.",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 3, "y": 5 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "(sum(delta(pinger_apiserver_latency_ms_sum{instance=~\"$instance\"}[5m])) by (nodeName))/(sum(delta(pinger_apiserver_latency_ms_count{instance=~\"$instance\"}[5m])) by (nodeName))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "DNS Latency Avg.",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 5 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "(sum(delta(pinger_internal_dns_latency_ms_sum{instance=~\"$instance\"}[5m])) by (nodeName))/(sum(delta(pinger_internal_dns_latency_ms_count{instance=~\"$instance\"}[5m])) by (nodeName))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Ping Pod Failure",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(delta(pinger_pod_ping_lost_total{instance=~\"$instance\"}[1m])) by (src_node_name)",
     "legendFormat": "src-{{src_node_name}}"
    },
    {
     "expr": "sum(delta(pinger_pod_ping_lost_total{instance=~\"$instance\"}[1m])) by (target_node_name)",
     "legendFormat": "target-{{target_node_name}}"
    }
   ]
  },
  {
   "title": "Ping Node Failure",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(delta(pinger_node_ping_lost_total{instance=~\"$instance\"}[5m])) by (src_node_name)",
     "legendFormat": "src-{{src_node_name}}"
    },
    {
     "expr": "sum(delta(pinger_node_ping_lost_total{instance=~\"$instance\"}[5m])) by (target_node_name)",
     "legendFormat": "target-{{target_node_name}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"kube-ovn-pinger\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"kube-ovn-pinger\",instance=~\"$instance\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{job=\"kube-ovn-pinger\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}